version: "3"

services:
  redis:
    image: redis
    container_name: resilience-poc-redis
    ports:
      - "6389:6379"
    volumes:
      - my-datavolume:/data
    networks:
      - backend
volumes:
  my-datavolume:

networks:
  backend: